# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1127b445292f4f16bbc4005afc7d3048c3a5ff99a8b44c8ca9323be08d98b2915a3e647316d7e1600aa6b99e2086ec00883e074384d6af8fc6c21dacab1afc8a

test:
  secret_key_base: a3fd060a0afbfa1fdec543880709961b57b94cb0c1af0a724fcc796f7a2409f83ee3a0ab0e60ad04260ad87a23916fe8a21e36fc957f28bb420a51f8d57d6547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
